name: bmi212
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - contourpy=1.0.5
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mahotas=1.4.13
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.4
  - nspr=4.33
  - nss=3.74
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - packaging=23.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.11.3
  - python-dateutil=2.8.2
  - python_abi=3.11
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
